format_version: v1.0
configName: SAMC21_Touch
folderName: SAMC21_Touch
frameworkPath: C:\H3_FW
processor: ATSAMC21J18A
projectName: SAMC21_Touch
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAMC21_DFP\3.8.119\samc21\atdf\ATSAMC21J18A.atdf
